package com.absinthe.libchecker.domain.app

import com.absinthe.libchecker.database.entity.LCItem
import java.io.OutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import okio.BufferedSink
import okio.buffer
import okio.sink

class ExportAppListUseCase(
  private val appListRepository: AppListRepository,
  private val metadata: AppListExportMetadata
) {

  suspend operator fun invoke(
    outputStream: OutputStream,
    format: Format
  ) {
    outputStream.sink().buffer().use { sink ->
      writeHeader(sink)

      val items = appListRepository.getItems()
      when (format) {
        Format.Markdown -> writeMarkdown(sink, items)
        Format.PlainText -> writePlainText(sink, items)
      }
    }
  }

  private fun writeHeader(sink: BufferedSink) {
    val formattedTime = SimpleDateFormat("yyyy-MM-dd, HH:mm:ss", Locale.getDefault())
      .format(Date(System.currentTimeMillis()))
    sink.writeLine("Generated by LibChecker ${metadata.versionName} (${metadata.versionCode})")
    sink.writeLine("Generated at $formattedTime")
    sink.writeLine()
  }

  private fun writeMarkdown(
    sink: BufferedSink,
    items: List<LCItem>
  ) {
    sink.writeLine(
      "| Package Name | App Name | Version Name | Version Code | System App | Abi | Target SDK | Play Store Link | F-Droid Link |"
    )
    sink.writeLine(
      "|--------------|----------|--------------|--------------|------------|-----|------------|-----------------|--------------|"
    )

    items.forEach { item ->
      val abiString = metadata.formatAbi(item.abi)
      sink.writeLine(
        "| ${item.packageName} | ${item.label} | ${item.versionName} | ${item.versionCode} | ${item.isSystem} | $abiString | ${item.targetApi} | [Link](https://play.google.com/store/apps/details?id=${item.packageName}) | [Link](https://f-droid.org/packages/${item.packageName}) |"
      )
    }
  }

  private fun writePlainText(
    sink: BufferedSink,
    items: List<LCItem>
  ) {
    items.forEach { item ->
      val abiString = metadata.formatAbi(item.abi)
      sink.writeLine("Package name: ${item.packageName}")
      sink.writeLine("App name: ${item.label}")
      sink.writeLine("Version name: ${item.versionName}")
      sink.writeLine("Version code: ${item.versionCode}")
      sink.writeLine("System App: ${item.isSystem}")
      sink.writeLine("Abi: $abiString")
      sink.writeLine("Target SDK: ${item.targetApi}")
      sink.writeLine("Play Store Link: https://play.google.com/store/apps/details?id=${item.packageName}")
      sink.writeLine("F-Droid Link: https://f-droid.org/packages/${item.packageName}")
      sink.writeLine()
    }
  }

  private fun BufferedSink.writeLine(value: String = "") {
    writeUtf8(value)
    writeUtf8(System.lineSeparator())
  }

  enum class Format {
    PlainText,
    Markdown
  }
}
