project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN

base_path: ".."
files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
