name: Feature Request / 功能请求
description: Suggest an idea for this project / 提出一个建议
labels: [ "enhancement" ]
title: "[FR] "
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist / 检查清单
      description: Ensure that our bug report form is appropriate for you. / 确保我们的错误报告表单适合您。
      options:
        - label: No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
          required: true
        - label: This suggestion does not depart from the original intention of LibChecker. / 这个建议不会背离 LibChecker 的初衷。
          required: true
  - type: textarea
    id: propose
    attributes:
      label: Enhancement propose / 改进目的
      description: Propose of the enhancement. / 改进有什么用
      placeholder: |
        Show your idea here.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution / 解决方案
      description: What's your solution for this enhancement? / 你会怎么完成这个改进？
      placeholder: |
        How to do it on your opinion? Or left this blank
  - type: textarea
    id: addition
    attributes:
      label: Additional info / 额外信息
      description: Everything else you consider worthy that we didn't ask for. / 任何你觉得值得说的。
